In [1]:
import pandas as pd
import numpy as np

#### Q1. Pandas version

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

#### Q2. Records count

In [6]:
df.describe().round(0)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.0,10000.0,10000.0,10000.0,9123.0,10000.0,9736.0,10000.0
mean,2000.0,4.0,2269.0,6.0,254.0,4287.0,19.0,30.0
std,14.0,1.0,183.0,1.0,23.0,266.0,1.0,3.0
min,1975.0,2.0,1590.0,4.0,171.0,3320.0,14.0,20.0
25%,1987.0,3.0,2150.0,6.0,239.0,4110.0,18.0,28.0
50%,2000.0,4.0,2270.0,6.0,254.0,4280.0,19.0,30.0
75%,2012.0,4.0,2390.0,6.0,270.0,4470.0,20.0,32.0
max,2024.0,5.0,3110.0,8.0,334.0,5460.0,24.0,41.0

#### Q3. Fuel types

In [7]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [8]:
df['fuel_type'].nunique()

3

#### Q4. Missing values

In [9]:
df.isnull()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False

In [10]:
# Checking the sum of missing values within the dataset
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
# Missing values for fuel type
df['fuel_type'].isnull().sum()

np.int64(0)

#### Q5. Max fuel efficiency

In [12]:
# Maximum fuel efficiency for entire cars
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [13]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [14]:
# Filtering cars in Asia
asia_cars = df[df['origin'] == 'Asia']

# Getting the maximum fuel efficiency
max_fuel_eff_asia = asia_cars['fuel_efficiency_mpg'].max()
max_fuel_eff_asia

np.float64(41.2)

#### Q6. Median value of horsepower

In [15]:
# Median of the horsepower column of the entire dataset
df['horsepower'].median()

np.float64(254.0)

In [16]:
# Most frequent values of the horsepower column
df['horsepower'].mode()

#Saving it into a variable
common_value_hp = df['horsepower'].mode()
common_value_hp

0    252.0
Name: horsepower, dtype: float64

In [17]:
# The most frequent value is 252.0
df['horsepower'].fillna(common_value_hp[0])

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [18]:
df['horsepower'].isnull().sum()

np.int64(877)

In [19]:
df['horsepower'].median()

np.float64(254.0)

#### Q7. Sumof weights

In [20]:
# All the cars in Asia
# Had this variable already 
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [21]:
# Selecting vehicle weight and model number (first 7 values)
asia_cars[['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [22]:
# Getting the underlying NumPy array
X = asia_cars[['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [23]:
XTX = X.T.dot(X) # Transpose of X multiplied by X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [24]:
XTX_inv = np.linalg.inv(XTX) # Using Numpy linear algebra method to compute an inverse
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [25]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200]) 
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [26]:
a = XTX_inv.dot(X.T) # multiplication of the inverse and the transpose of X
w = a.dot(y) # the output above multiplied by y
w

array([0.13644777, 0.2327492 ])

In [27]:
# Sum of the elements in the results above
result_sum = w.sum()
result_sum

np.float64(0.36919696904925486)